### ISSUE TITLE
test failed

### ISSUE THREAD

**Issue by bluet** [sintaxi/jjade#1]
I came from harp -> terraform -> jjade and trying to resolve security warnings from `npm audit` in projects with `harp` as dependency.

I did a clean clone and did `npm i` but got errors from `npm run test`:
  1) filters coffeescript
  2) include filter
  3) should instantiate objects with lineno and filename properties

Some further info:
```js
  261 passing (13s)
  3 failing

  1) filters coffeescript:

      AssertionError: expected '"<scripttype=\\"text/javascript\\">(function(){varregexp;regexp=/\\\\n/;}).call(this);(function(){}).call(this);</script>"' to be '"<scripttype=\\"text/javascript\\">(function(){varregexp;regexp=/\\\\n/;}).call(this);(function(){varn;n={square:function(n){returnn*n}}}).call(this);</script>"'
      + expected - actual

      -"<scripttype=\"text/javascript\">(function(){varregexp;regexp=/\\n/;}).call(this);(function(){}).call(this);</script>"
      +"<scripttype=\"text/javascript\">(function(){varregexp;regexp=/\\n/;}).call(this);(function(){varn;n={square:function(n){returnn*n}}}).call(this);</script>"
      
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value (node_modules/should/cjs/should.js:356:19)
      at Context.<anonymous> (test/run.js:68:42)
  

  2) include filter:

      AssertionError: expected '"<html><body><p>Just<em>some</em>markdown<strong>tests</strong>.</p><p>Withnewline.</p><script>(function(){}).call(this);</script><script>(function(){varmath;math={square:function(value){returnvalue*value;}};}).call(this);</script></body></html>"' to be '"<html><body><p>Just<em>some</em>markdown<strong>tests</strong>.</p><p>Withnewline.</p><script>(function(){varn;n={square:function(n){returnn*n}}}).call(this);</script><script>(function(){varmath;math={square:function(value){returnvalue*value;}};}).call(this);</script></body></html>"'
      + expected - actual

      -"<html><body><p>Just<em>some</em>markdown<strong>tests</strong>.</p><p>Withnewline.</p><script>(function(){}).call(this);</script><script>(function(){varmath;math={square:function(value){returnvalue*value;}};}).call(this);</script></body></html>"
      +"<html><body><p>Just<em>some</em>markdown<strong>tests</strong>.</p><p>Withnewline.</p><script>(function(){varn;n={square:function(n){returnn*n}}}).call(this);</script><script>(function(){varmath;math={square:function(value){returnvalue*value;}};}).call(this);</script></body></html>"
      
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value (node_modules/should/cjs/should.js:356:19)
      at Context.<anonymous> (test/run.js:68:42)
  

  3) DebugItem
       should instantiate objects with lineno and filename properties:

      AssertionError: expected DebugItem { lineno: 42, filename: '/path/to/file' } to equal Object { lineno: 42, filename: '/path/to/file' } (because A and B have different prototypes)
      + expected - actual


      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value (node_modules/should/cjs/should.js:356:19)
      at Context.<anonymous> (test/unit.js:46:15)
  

```

**Comment by bluet** [comment]
@sintaxi can you take a look? Thanks!

**Comment by bluet** [comment]
There's a security warning from `npm audit` and I wanna help on solving the problem, but I'm stuck on running test lol

**Comment by bluet** [comment]
@sintaxi  any updates?
